version: "3.9"
services:
  timesheet:
    image: rzblue/timesheet
    environment:
      - TS_DATABASE_HOST=postgres
      - TS_DATABASE=${DB_NAME}
      - TS_DATABASE_USER=${DB_USER}
      - TS_DATABASE_PASSWORD=${DB_PASSWORD}
      - TS_DEFAULT_LOGIN=signup@team900.org
      - TS_TEAM_NAME=Timberwolves
      - TS_TEAM_NUMBER=7540
      - TS_PORT=3000
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
